from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time

s = Service('C:/Users/gsan1/PycharmProjects/chromedriver.exe')
driver = webdriver.Chrome(service=s)
driver.get("https://qahacking.guru/index.php/magazin")
driver.set_window_size(1336, 786)
time.sleep(5)
driver.find_element(By.CSS_SELECTOR, ".productitem_2 .btn-success").click()
driver.find_element(By.ID, "jshop_attr_id1").click()
dropdown = driver.find_element(By.ID, "jshop_attr_id1")
dropdown.find_element(By.XPATH, "//option[. = 'Red']").click()
driver.find_element(By.NAME, "freeattribut[1]").click()
driver.find_element(By.NAME, "freeattribut[1]").send_keys("3")
driver.find_element(By.CSS_SELECTOR, ".prod_free_attribs").click()
driver.find_element(By.ID, "quantity").click()
driver.find_element(By.ID, "quantity").send_keys("5")
driver.find_element(By.CSS_SELECTOR, ".btn-buy").click()
driver.find_element(By.CSS_SELECTOR, ".cart_reload > img").click()
driver.find_element(By.LINK_TEXT, "Оформить заказ").click()
driver.find_element(By.ID, "f_name").click()
driver.find_element(By.ID, "f_name").send_keys("Иван")
driver.find_element(By.ID, "l_name").send_keys("Иванов")
driver.find_element(By.ID, "email").send_keys("email@domain.com")
driver.find_element(By.ID, "street").send_keys("Ленина 12")
driver.find_element(By.ID, "zip").send_keys("445028")
driver.find_element(By.ID, "city").send_keys("Тольятти")
driver.find_element(By.ID, "state").send_keys("Самарская")
driver.find_element(By.ID, "phone").send_keys("+79272149033")
driver.find_element(By.ID, "country").click()
dropdown = driver.find_element(By.ID, "country")
dropdown.find_element(By.XPATH, "//option[. = 'Russian Federation']").click()
driver.find_element(By.NAME, "next").click()
driver.find_element(By.ID, "payment_submit").click()
driver.find_element(By.ID, "shipping_method_2").click()
driver.find_element(By.CSS_SELECTOR, ".button").click()
driver.find_element(By.ID, "agb").click()
driver.find_element(By.NAME, "finish_registration").click()
time.sleep(5)
print("ТЕСТ УСПЕШНО ПРОЙДЕН!")
driver.close()